var ps=require("fs")
// ps.mkdirSync("Hello")
ps.writeFileSync("Hello/User.txt","Hitexa")
ps.appendFileSync("Hello/User.txt"," How are you?")
var data=ps.readFileSync("Hello/User.txt","Utf-8")
console.log(data)
// if utf-8 not written in  readFileSync parameter then write data.toString()
console.log(data.toString())
ps.renameSync("Hello/User.txt","Hello/User2.txt")
ps.unlinkSync("Hello/User2.txt")
ps.rmdirSync("Hello")